//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPie.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniPie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on.
        /// </summary>
        public static string About_BasedOn {
            get {
                return ResourceManager.GetString("About_BasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used 3rd party libraries.
        /// </summary>
        public static string About_UsedThirdParty {
            get {
                return ResourceManager.GetString("About_UsedThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MiniPie....
        /// </summary>
        public static string App_AboutMiniPie {
            get {
                return ResourceManager.GetString("App_AboutMiniPie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string App_Exit {
            get {
                return ResourceManager.GetString("App_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Track.
        /// </summary>
        public static string App_Next {
            get {
                return ResourceManager.GetString("App_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        public static string App_PlayPause {
            get {
                return ResourceManager.GetString("App_PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Track.
        /// </summary>
        public static string App_Previous {
            get {
                return ResourceManager.GetString("App_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string App_Settings {
            get {
                return ResourceManager.GetString("App_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Down.
        /// </summary>
        public static string App_VolumeDown {
            get {
                return ResourceManager.GetString("App_VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Up.
        /// </summary>
        public static string App_VolumeUp {
            get {
                return ResourceManager.GetString("App_VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string Enum_ApplicationSize_Large {
            get {
                return ResourceManager.GetString("Enum_ApplicationSize_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Enum_ApplicationSize_Medium {
            get {
                return ResourceManager.GetString("Enum_ApplicationSize_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string Enum_ApplicationSize_Small {
            get {
                return ResourceManager.GetString("Enum_ApplicationSize_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string Enum_KeyModifiers_Alt {
            get {
                return ResourceManager.GetString("Enum_KeyModifiers_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        public static string Enum_KeyModifiers_Ctrl {
            get {
                return ResourceManager.GetString("Enum_KeyModifiers_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        public static string Enum_KeyModifiers_None {
            get {
                return ResourceManager.GetString("Enum_KeyModifiers_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string Enum_KeyModifiers_Shift {
            get {
                return ResourceManager.GetString("Enum_KeyModifiers_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show MiniPie always on top of other windows.
        /// </summary>
        public static string Settings_AlwaysOnTop {
            get {
                return ResourceManager.GetString("Settings_AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application size:.
        /// </summary>
        public static string Settings_ApplicationSize {
            get {
                return ResourceManager.GetString("Settings_ApplicationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiniPie caches all requested cover images to save your bandwidth. If you have troubles with some images you can use the button below to clear the cache..
        /// </summary>
        public static string Settings_CacheClearLabel {
            get {
                return ResourceManager.GetString("Settings_CacheClearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear cover cache.
        /// </summary>
        public static string Settings_ClearCache {
            get {
                return ResourceManager.GetString("Settings_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Settings_Common {
            get {
                return ResourceManager.GetString("Settings_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current cache size:.
        /// </summary>
        public static string Settings_CurrenCacheSize {
            get {
                return ResourceManager.GetString("Settings_CurrenCacheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable animations (if your pc can&apos;t handle the awesomeness).
        /// </summary>
        public static string Settings_DisableAnimations {
            get {
                return ResourceManager.GetString("Settings_DisableAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Hotkeys.
        /// </summary>
        public static string Settings_EnableHotkeys {
            get {
                return ResourceManager.GetString("Settings_EnableHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide MiniPie when Spotify is not running.
        /// </summary>
        public static string Settings_HideIfSpotifyClosed {
            get {
                return ResourceManager.GetString("Settings_HideIfSpotifyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string Settings_Hotkeys {
            get {
                return ResourceManager.GetString("Settings_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start MiniPie after I log into my computer.
        /// </summary>
        public static string Settings_StartWithWindows {
            get {
                return ResourceManager.GetString("Settings_StartWithWindows", resourceCulture);
            }
        }
    }
}
